### ISSUE TITLE
[eyes-cypress] eyesCheckWindow doesn't capture :hover css changes

### ISSUE THREAD

**Issue by ronyf** [applitools/eyes.sdk.javascript1#718]
I have a css change that occurs on my [ag-grid](https://www.ag-grid.com/) once I hover over a row.
The ["fake"](https://github.com/cypress-io/cypress/issues/10#issuecomment-731839616) hover ways didn't work for me with cypress, so I had to do ["realHover"](https://github.com/dmtrKovalenko/cypress-real-events#cyrealhover)
Unfortunately, this state isn't caught by eyes and I don't see it in the captured screen.

```
myPage.getCell(...).realHover();

cy.eyesCheckWindow({
  tag: 'hover row',
});
```

Any ideas?

**Comment by kyryloonufriiev** [comment]
Hi @ronyf since cypress uses an Ultrafast Grid to take screenshots of your application across multiple screen sizes and environments it has some limitations, one of them is that your local cursor position is not stored (it means hover effects either). You can try to achieve this result with the `beforeCaptureScreenshot` hook. You can write a plain js there and it will be executed inside the grid environment on each browser/size/device.
Here is the [documentation](https://github.com/applitools/eyes.sdk.javascript1/blob/master/packages/eyes-cypress/README.md#beforecapturescreenshot-a-script-that-runs-after-the-page-is-loaded-but-before-taking-the-screenshot-for-example) for this feature.

**Comment by amitzur** [comment]
Hi @ronyf ,

For feature requests, feedback, and bug reports, please contact support@applitools.com
